services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    image: ghcr.io/asolmaz55/group6-backend:latest
    build:
      context: ./backend
    ports:
      - "9000:9000"
    environment:
      REDIS_DNS: redis
    depends_on:
      - redis

  frontend:
    image: ghcr.io/asolmaz55/group6-frontend:latest
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      BACKEND_DNS: backend
      BACKEND_PORT: "9000"
    depends_on:
      - backend